### ISSUE TITLE
Super Mario Odyssey coin count modifies unrelated data, not coin count.

### ISSUE THREAD

**Issue by ValliantStorme** [thomasnet-mc/EdiZon#11]
Coin Count is listed as being 79, while in-game coin count is 5453.
(Odyssey 1.0.1 on firmware 4.1.0)

**Comment by WerWolv98** [comment]
@ValliantStrome The offsets are only valid for the latest version 1.2.0. Until we have a real BYML parser we can't do anything about that

**Comment by ValliantStorme** [comment]
Ah, ok! Good to know
