### ISSUE TITLE
int is too small for save editing.....

### ISSUE THREAD

**Issue by Luro02** [thomasnet-mc/EdiZon#17]
There is only int as an option available and it is limited to "0x7F FF FF FF" (2 147 483 647) but for example Xenoblade Chronicles 2 is limited to "0xFF FF FF" (4 294 967 295) (uint32 ?)
https://youtu.be/yC6B6Vyvqx8 (sample video...)

**Comment by WerWolv98** [comment]
Yeah I have to add another uint widget next to the int one. I'll fix that when I have time. (Probably not this week)

**Comment by Luro02** [comment]
the same goes for float :/
