### ISSUE TITLE
Title icons scrolling

### ISSUE THREAD

**Issue by maciak** [thomasnet-mc/EdiZon#2]
Hi,
Just had some fun with it and scroling through titles works weird. It jumps in strange way that it's confusing and I have 15 titles and last one in top row shows for some time but when I get to it it's offscreen. 
![2018060417110500-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/1494232/40925864-ff8fb6e8-681a-11e8-9b8d-24ec53135e59.jpg)
Like on this image.

Touch selecting titles is a bit wonky too. And I cannot select last titles to the right at all.

**Comment by WerWolv98** [comment]
Thank you! I never tested an uneven number of titles. Neither did I test touch with more than 10 titles. Everything should be fixed now with the latest commit. Thanks a lot!
