### ISSUE TITLE
Edizon didnt backup save data from games on 5.1.0

### ISSUE THREAD

**Issue by Initializist** [thomasnet-mc/EdiZon#4]
Hi, I tried to back up my games using Edizon. Even though the directory and game tiled file were created, there was no save data under the file.

**Comment by WerWolv98** [comment]
What game did you try to backup? Was there any error displayed after the backup? Did you have a save for that game?

**Comment by Initializist** [comment]
I tried to back up Pokemon Quest, Monster Hunter, Splatoon 2, BOTW in English, Japanese, and Simplified Chinese. At first, the message said data is back up successfully and there was no data present under the Edizon directory at SD root.  when I hit the back up the second time a message saying ''an error occurred while back up'' show up.

**Comment by WerWolv98** [comment]
Could it be possible that your username has some Japanese/Chinese symbols in it?

**Comment by Initializist** [comment]
Yes, my user name is in Japanese. :(
