### ISSUE TITLE
Feature suggestion; Values

### ISSUE THREAD

**Issue by borntohonk** [thomasnet-mc/EdiZon#5]
Improve upon widget for values to choose between specific values i.e.
This would reduce bad math / improper use from people sliding up and down between min/max from choosing incorrect values. Additional description of what a value is would be nice too.

BOTW specific examples:
( https://github.com/marcrobledo/savegame-editors/blob/master/zelda-botw/index.html#L83 )

Value 1 = "4", "1 Hearts"
Value 2 =" 8", "2 Hearts"
value 3 = "12", "3 Hearts"

( https://github.com/marcrobledo/savegame-editors/blob/master/zelda-botw/index.html#L120)

Value 1="1148846080", "1 wheel of stamina"
Value 2="1150681088", "1.2 Wheel of stamina"
Value 3="1152319488", "1.4 Wheel of stamina"

something like that

**Comment by thomasnet-mc** [comment]
Would be implemented w/ like type=list?

**Comment by WerWolv98** [comment]
Already implemented but a bit buggy still. I asked him to make an issue here ^^
