### ISSUE TITLE
[README] Properly clarify JSON fields

### ISSUE THREAD

**Issue by Favna** [thomasnet-mc/EdiZon#8]
There are a couple of discrepancies in the README concerning the editor that make it unclear what an implementator should be doing.

1. The field reference mentions `validSAveFileNames` but this field is not seen in the example JSON
2. The example has a field `files` but this is not in the reference
3. It is not made clear how `saveFilePaths` should be structured. If the saves are at `/EdiZon/{TITLEID}/{DATETIME}`, should the field say `/EdiZon/{TITLEID}/*` or `/EdiZon/{TITLEID}` or whatever else? This needs clarifying.
4. Is the `offsetAddress` the starting byte? By which I mean if it should write `FF FF FF FF` to the area of `1A AB AB AB` should the structure be:

```json
{
	"items": [{
		"name": "Example",
		"offsetAddress": "1AAB",
		"address": "ABAB",
		"widget": {
			"type": "int",
			"minValue": 0,
			"maxValue": 9999
		}
	}]
}
```

Please clarify the proper structure when people want to write certain bytes to a certain region. Example of how people reference what to write where can be found on [this gbatemp thread](https://gbatemp.net/threads/request-hyrule-warriors-de-editor.506421/page-8#post-8115410) (linking a comment of my own as I address writing data to a specific region in here)

---

Lastly, EdiZon currently stores the save files in a lowercase TitleID path but the JSON file needs to be saved as UPPERCASE. I would very strongly recommend either allowing MiXeDCase on the editor files, OR making all the saved files UPPERCASE in the next release. Hold  to 1 casing style throughout an entire project!

**Comment by WerWolv98** [comment]
The whole documention will be redone when releasing the next update since almost everything has changed. I'll try to make it a lot more clearer this time.

For the naming, that was fixed some time ago. Will be implemented in the next version.

**Comment by Favna** [comment]
Sounds good. Looking forward to it.
